services:
  node:
    build: .
    container_name: node
    expose:
      - '3000'
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: npm start

    
  mongo:
    image: mongo:latest
    container_name: mongo
    expose:
      - '27017' 
    restart: always
    volumes:
      - mongo_data:/data/db

  
volumes:
  mongo_data: