services:

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: myapp
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}
    command: npm start
    volumes:
      - mongo_data:/data/db
    networks:
      - node-mongo-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - node-mongo-network  
   
  
volumes:
  mongo_data: 

networks:
  node-mongo-network:
    driver: bridge